import type { GenreId, GenreProfile } from './types';

export const GENRES: Record<GenreId, GenreProfile> = {
  literary: {
    id: 'literary',
    name: 'Literary Fiction',
    description: 'Long, flowing sentences. Em-dashes, semicolons, curly quotes.',
    quoteStyle: 'curly',
    dashStyle: 'em',
    oxfordComma: true,
    useEllipsisGlyph: true,
    sceneBreakGlyph: '* * *',
  },
  fantasy: {
    id: 'fantasy',
    name: 'Fantasy',
    description: 'Invented names and places, em-dashes, curly quotes.',
    quoteStyle: 'curly',
    dashStyle: 'em',
    oxfordComma: true,
    useEllipsisGlyph: true,
    sceneBreakGlyph: '❖',
  },
  'sci-fi': {
    id: 'sci-fi',
    name: 'Science Fiction',
    description: 'Technical terms, en-dashes for ranges, curly quotes.',
    quoteStyle: 'curly',
    dashStyle: 'en',
    oxfordComma: true,
    useEllipsisGlyph: true,
    sceneBreakGlyph: '— — —',
  },
  thriller: {
    id: 'thriller',
    name: 'Thriller',
    description: 'Short, punchy sentences. Em-dashes for interruption.',
    quoteStyle: 'curly',
    dashStyle: 'em',
    oxfordComma: false,
    useEllipsisGlyph: false,
    sceneBreakGlyph: '#',
  },
  mystery: {
    id: 'mystery',
    name: 'Mystery / Crime',
    description: 'Measured cadence, ellipses for suspense, curly quotes.',
    quoteStyle: 'curly',
    dashStyle: 'em',
    oxfordComma: true,
    useEllipsisGlyph: true,
    sceneBreakGlyph: '* * *',
  },
  romance: {
    id: 'romance',
    name: 'Romance',
    description: 'Warm cadence, em-dashes, curly quotes, ellipses.',
    quoteStyle: 'curly',
    dashStyle: 'em',
    oxfordComma: true,
    useEllipsisGlyph: true,
    sceneBreakGlyph: '♥',
  },
  horror: {
    id: 'horror',
    name: 'Horror',
    description: 'Fragmented tension. Ellipses and em-dashes.',
    quoteStyle: 'curly',
    dashStyle: 'em',
    oxfordComma: false,
    useEllipsisGlyph: true,
    sceneBreakGlyph: '† † †',
  },
  ya: {
    id: 'ya',
    name: 'Young Adult',
    description: 'Contemporary voice, curly quotes, em-dashes.',
    quoteStyle: 'curly',
    dashStyle: 'em',
    oxfordComma: true,
    useEllipsisGlyph: false,
    sceneBreakGlyph: '* * *',
  },
  generic: {
    id: 'generic',
    name: 'General Fiction',
    description: 'Sensible defaults with straight quotes.',
    quoteStyle: 'straight',
    dashStyle: 'em',
    oxfordComma: true,
    useEllipsisGlyph: false,
    sceneBreakGlyph: '* * *',
  },
};

export const GENRE_LIST: GenreProfile[] = Object.values(GENRES);

export function getGenre(id: GenreId): GenreProfile {
  return GENRES[id] ?? GENRES.generic;
}
